### ISSUE TITLE
Mutliple yaml includes causes the metadata enumerations to mismatch with traces

### ISSUE THREAD

**Issue by prakashanurag** [efficios/barectf#17] opened 2019-12-16 17:46 UTC
Here is an exemplary include hierarchy:
1. a.yaml -> b.yaml ->events.yaml
2. a.yaml -> events.yaml
3. a.yaml has enumerations

Issue: The generated metadata has incorrect enumeration number mapping.
Version: Barectf 2.3.0

**Comment by eepp** [comment] 2020-06-19 20:01
This is not a bug.

[_Including external YAML files_](https://github.com/efficios/barectf/wiki/Including-external-YAML-files) says, for arrays (which the `members` property is because barectf follows the [CTF/TSDL model](https://diamon.org/ctf/#spec4.1.8)):

> * Property exists in base object:
>   * Base property is an array: new elements are appended to base array
>   * Base property is not an array: base property is replaced by included property
> * Property does not exist in base object: included property is appended to base object

The observed behaviour above is normal considering that:

* New elements are appended to base array, as quoted above.
* You can include the same file multiple times.

Both points above are features, which is why we can't change that behaviour in barectf.

Closing this.

**Closed by eepp** 2020-06-19 20:01 UTC
Labels: invalid
